"""Shared data contracts used across the flight pipeline."""

SOURCE_COLUMN_RENAME_MAP = {
    "YEAR": "year",
    "QUARTER": "quarter",
    "MONTH": "month",
    "DAY_OF_MONTH": "day_of_month",
    "DAY_OF_WEEK": "day_of_week",
    "FL_DATE": "flight_date",
    "OP_UNIQUE_CARRIER": "reporting_airline_code",
    "OP_CARRIER_AIRLINE_ID": "reporting_airline_id",
    "TAIL_NUM": "tail_number",
    "OP_CARRIER_FL_NUM": "flight_number",
    "ORIGIN_AIRPORT_ID": "origin_airport_id",
    "ORIGIN": "origin_airport_code",
    "ORIGIN_CITY_NAME": "origin_city_name",
    "ORIGIN_STATE_ABR": "origin_state_code",
    "ORIGIN_STATE_NM": "origin_state_name",
    "DEST_AIRPORT_ID": "destination_airport_id",
    "DEST": "destination_airport_code",
    "DEST_CITY_NAME": "destination_city_name",
    "DEST_STATE_ABR": "destination_state_code",
    "DEST_STATE_NM": "destination_state_name",
    "CRS_DEP_TIME": "scheduled_departure_time",
    "DEP_TIME": "actual_departure_time",
    "DEP_DELAY": "departure_delay_minutes_signed",
    "DEP_DELAY_NEW": "departure_delay_minutes",
    "DEP_DEL15": "departure_delayed_15",
    "DEP_TIME_BLK": "departure_time_block",
    "TAXI_OUT": "taxi_out_minutes",
    "TAXI_IN": "taxi_in_minutes",
    "CRS_ARR_TIME": "scheduled_arrival_time",
    "ARR_TIME": "actual_arrival_time",
    "ARR_DELAY": "arrival_delay_minutes_signed",
    "ARR_DELAY_NEW": "arrival_delay_minutes",
    "ARR_DEL15": "arrival_delayed_15",
    "ARR_TIME_BLK": "arrival_time_block",
    "CANCELLED": "cancelled",
    "CANCELLATION_CODE": "cancellation_code",
    "DIVERTED": "diverted",
    "CRS_ELAPSED_TIME": "scheduled_elapsed_minutes",
    "ACTUAL_ELAPSED_TIME": "actual_elapsed_minutes",
    "AIR_TIME": "air_time_minutes",
    "FLIGHTS": "flight_count",
    "DISTANCE": "distance_miles",
    "DISTANCE_GROUP": "distance_group",
    "CARRIER_DELAY": "carrier_delay_minutes",
    "WEATHER_DELAY": "weather_delay_minutes",
    "NAS_DELAY": "national_air_system_delay_minutes",
    "SECURITY_DELAY": "security_delay_minutes",
    "LATE_AIRCRAFT_DELAY": "late_aircraft_delay_minutes",
}

SOURCE_COLUMNS = list(SOURCE_COLUMN_RENAME_MAP)

SOURCE_FLIGHT_KEY_COLUMNS = [
    "FL_DATE",
    "OP_CARRIER_AIRLINE_ID",
    "OP_CARRIER_FL_NUM",
    "ORIGIN_AIRPORT_ID",
    "DEST_AIRPORT_ID",
    "CRS_DEP_TIME",
]

CLEAN_FLIGHT_KEY_COLUMNS = [
    "flight_date",
    "reporting_airline_id",
    "flight_number",
    "origin_airport_id",
    "destination_airport_id",
    "scheduled_departure_time",
]

DELAY_CAUSE_COLUMNS = [
    "carrier_delay_minutes",
    "weather_delay_minutes",
    "national_air_system_delay_minutes",
    "security_delay_minutes",
    "late_aircraft_delay_minutes",
]

WAREHOUSE_REQUIRED_CLEAN_COLUMNS = [
    "flight_date",
    "reporting_airline_id",
    "reporting_airline_code",
    "flight_number",
    "origin_airport_id",
    "origin_airport_code",
    "destination_airport_id",
    "destination_airport_code",
    "scheduled_departure_time",
    "scheduled_arrival_time",
    "flight_count",
    "distance_miles",
    "cancelled",
    "diverted",
    "flight_status",
    "route_code",
    "delay_cause_reported",
    "carrier_delay_minutes",
    "weather_delay_minutes",
    "national_air_system_delay_minutes",
    "security_delay_minutes",
    "late_aircraft_delay_minutes",
    "total_reported_delay_minutes",
]
